name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2]
        rails: ["7.0", "7.1"]
        db: [sqlite, postgres, mysql, mariadb]

    services:
      postgres:
        image: postgres:15
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:8
        ports: [3306:3306]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: safe_migrations_test
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=5

      mariadb:
        image: mariadb:latest
        ports: [3307:3306]
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: safe_migrations_test
        options: >-
          --health-cmd="healthcheck.sh --connect"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=5

    env:
      RAILS_ENV: test
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: safe_migrations_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safe_migrations_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle add rails -v "~> ${{ matrix.rails }}" --skip-install
          bundle install

      - name: Prepare database
        run: |
          case ${{ matrix.db }} in
            sqlite)
              export DATABASE_URL="sqlite3::memory:"
              ;;
            postgres)
              export DATABASE_URL="postgres://postgres:postgres@localhost:5432/safe_migrations_test"
              ;;
            mysql)
              export DATABASE_URL="mysql2://root:root@127.0.0.1:3306/safe_migrations_test"
              ;;
            mariadb)
              export DATABASE_URL="mysql2://root:root@127.0.0.1:3307/safe_migrations_test"
              ;;
          esac

          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV

      - name: Run specs
        run: bundle exec rspec
